### ISSUE TITLE
[QUESTION] How to fix the "an empty namespace may not be set during creation" error

### ISSUE THREAD

**Issue by diviner524** [awslabs/crossplane-on-eks#104]
#### Please describe your quesiton here
Hi,

I saw the same error as mentioned in:

https://github.com/awslabs/crossplane-on-eks/blob/main/doc/debugging.md#composition

I noticed the document mentioned `For this particular issue, we need to specify the namespace for the IRSA resource.`

Could you please elaborate how can we specify the namespace in a `Composite` and how did you fix this? 

Should this be done through a patch/parameter, something like:

Fix 1: 
```
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.managedResourceNamespace
      toFieldPath: metadata.namespace
```

Or did you fix it by 

Fix 2: Adding metadata.namespace in the `base` of Composition directly.

I tried both and it seems none of them worked for me.

Fix 1 is giving me a new error:

```
  Warning  ComposeResources         20s (x6 over 77s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot compose resources: cannot associate composed resources with Composition resource templates: cannot get composed resource: an empty namespace may not be set when a resource name is provided
```

Fix 2 is not making any difference as I suspect the namespace specified in base is discarded by crossplane controller.

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by nabuskey** [comment]
It's complaining about creating a namespaced resource without specifying a namespace. So you should be able to specify it via patch like this:

```yaml
type: FromCompositeFieldPath
fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
toFieldPath: metadata.namespace

```
See:
https://github.com/awslabs/crossplane-on-eks/blob/d8ff2a8e9f19d7d09a46e7c02182056abbbacc1c/compositions/aws-provider/irsa/irsa-role-only.yaml#L63

When you create a composite resource claim, the corresponding composite resource is created with few labels that contain some information about the claim. `crossplane.io/claim-namespace` is one of them.

You typically run into this kind of issue when you are creating claims in compositions, which you should avoid if you can.

**Comment by nabuskey** [comment]
If you have more questions regarding this, please feel free to reopen.

**Comment by diviner524** [comment]
Thanks @nabuskey for sharing the solution!
