### ISSUE TITLE
[QUESTION] Will this be come as official AWS EKS addon with full support?

### ISSUE THREAD

**Issue by jkroepke** [awslabs/crossplane-on-eks#123]
#### Please describe your quesiton here
I would like to know, if Crossplane on EKS is something that is planned to be offered as official EKS Addon?

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by nabuskey** [comment]
Unfortunately, we cannot provide answers to your question here since EKS products are not handled by our team. 
You may want to check this repository instead: https://github.com/aws/containers-roadmap
