### ISSUE TITLE
[Bug]: terraform init error subdir "modules/kubernetes-addons/helm-addon" not found

### ISSUE THREAD

**Issue by csantanapr** [awslabs/crossplane-on-eks#139]
### Welcome to AWS Blueprints for Crossplane!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/crossplane-aws-blueprints/issues) and didn't find any.

### AWS Blueprints for Crossplane Release version

latest

### What is your environment, configuration and the example used?

latest

### What did you do and What did you see instead?

```
cd bootstrap/terraform/
terraform init
```

Errors with
```
➜  terraform git:(main) ✗ terraform init                                                                                                                    arn:aws:eks:us-west-2:015299085168:cluster/cluster-1-dev

Initializing the backend...
Initializing modules...
Downloading git::https://github.com/aws-ia/terraform-aws-eks-blueprints.git for eks_blueprints_crossplane_addons.portworx.helm_addon...
Downloading git::https://github.com/aws-ia/terraform-aws-eks-blueprints.git for eks_blueprints_crossplane_addons.sysdig_agent.helm_addon...
╷
│ Error: Failed to expand subdir globs
│ 
│ subdir "modules/kubernetes-addons/helm-addon" not found
╵

╷
│ Error: Failed to expand subdir globs
│ 
│ subdir "modules/kubernetes-addons/helm-addon" not found
```

**Comment by Sebs030** [comment]
Hi I have a similar issue when i try to use the module "eks_blueprints_kubernetes_addons" example provided on your [page] (https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/). Running `terraform init` results in `Initializing the backend...
Initializing modules...
Downloading git::https://github.com/aws-ia/terraform-aws-eks-blueprints.git for kubernetes_addons...
╷
│ Error: Failed to expand subdir globs
│
│ subdir "modules/kubernetes-addons" not found`
