### ISSUE TITLE
[Bug]: kube-prometheus-stack-grafana in a crash loop back off upon first install

### ISSUE THREAD

**Issue by askulkarni2** [awslabs/crossplane-on-eks#165]
### Welcome to AWS Blueprints for Crossplane!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/crossplane-aws-blueprints/issues) and didn't find any.

### AWS Blueprints for Crossplane Release version

v0.1.0

### What is your environment, configuration and the example used?

https://github.com/awslabs/crossplane-on-eks/tree/main/bootstrap/terraform

### What did you do and What did you see instead?

Ran `terraform apply`. Expected to see all pods up and running. The kube-prometheus-stack-grafana pod is in a crash loop backoff with this error in the logs.

```
grafana logger=provisioning t=2024-02-01T14:26:19.066649715Z level=error msg="Failed to provision data sources" error="Datasource provisioning error: datasource.yaml config is invalid. Only one datasource per organization can be marked as default"
grafana Error: ✗ Datasource provisioning error: datasource.yaml config is invalid. Only one datasource per organization can be marked as default
```

**Comment by candonov** [comment]
Fixed.
