### ISSUE TITLE
[Bug]: Use of gavinbunney/kubectl is error prone

### ISSUE THREAD

**Issue by askulkarni2** [awslabs/crossplane-on-eks#166]
### Welcome to AWS Blueprints for Crossplane!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/crossplane-aws-blueprints/issues) and didn't find any.

### AWS Blueprints for Crossplane Release version

v0.1.0

### What is your environment, configuration and the example used?

https://github.com/awslabs/crossplane-on-eks/tree/main/bootstrap/terraform

### What did you do and What did you see instead?

The [gavinbunney/kubectl](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) provider is no longer actively maintained and is known to be very unstable and unusable at this point. I did a minor change in `main.tf` and reapplied and saw these errors which are typical symptoms of the unstable state of the provider. Across EKS Blueprints we are discontinuing the use of the `kubectl_manifest` and recommending folks to use the Hashicorp [terraform-provider-kubernetes](https://github.com/hashicorp/terraform-provider-kubernetes) or package up the yaml files as inline helm charts.

```
Error: cluster failed to fetch resource from kubernetes: the server could not find the requested resource
│ 
│   with kubectl_manifest.environmentconfig,
│   on main.tf line 196, in resource "kubectl_manifest" "environmentconfig":
│  196: resource "kubectl_manifest" "environmentconfig" {
│ 
╵
╷
│ Error: upbound-aws-controller-config failed to fetch resource from kubernetes: the server could not find the requested resource
│ 
│   with kubectl_manifest.upbound_aws_controller_config[0],
│   on main.tf line 289, in resource "kubectl_manifest" "upbound_aws_controller_config":
│  289: resource "kubectl_manifest" "upbound_aws_controller_config" {
│ 
╵
╷
│ Error: kubernetes-controller-config failed to fetch resource from kubernetes: the server could not find the requested resource
│ 
│   with kubectl_manifest.kubernetes_controller_config[0],
│   on main.tf line 418, in resource "kubectl_manifest" "kubernetes_controller_config":
│  418: resource "kubectl_manifest" "kubernetes_controller_config" {
│ 
╵
╷
│ Error: helm-controller-config failed to fetch resource from kubernetes: the server could not find the requested resource
│ 
│   with kubectl_manifest.helm_controller_config[0],
│   on main.tf line 482, in resource "kubectl_manifest" "helm_controller_config":
│  482: resource "kubectl_manifest" "helm_controller_config" {
```

**Comment by edgarsilva948** [comment]
@candonov the PR #193 fixes this.

**Comment by candonov** [comment]
Thank you for fixing that @edgarsilva948 !
