### ISSUE TITLE
[FEATURE] Parity with Upbound AWS provider

### ISSUE THREAD

**Issue by csantanapr** [awslabs/crossplane-on-eks#99]
#### Is your feature request related to a problem? Please describe

The repository offers [Compositions](https://github.com/awslabs/crossplane-on-eks/tree/main/compositions), and [examples](https://github.com/awslabs/crossplane-on-eks/tree/main/examples/aws-provider) with the upstream Crossplane AWS provider, we would like to have similar compositions and examples using Upbound AWS provider.

#### Describe the solution you'd like

Go over the Compositions and Examples present and create parallel folders to have parity, any opportunities to improve them are welcome.

#### Describe alternatives you've considered
None

#### Additional context
Some of these work already started by adding boostrap assets and instructions to install the Upbound AWS provider using [eksctl](https://github.com/awslabs/crossplane-on-eks/tree/main/bootstrap/eksctl) and [terraform](https://github.com/awslabs/crossplane-on-eks/tree/main/bootstrap/terraform).

**Comment by csantanapr** [comment]
This can be done in collaborative effort, please use this issue to coordinate.

If you plan to work on particular composition and example, please add a comment here, then associate the PR once you have  some code to review or draft PR.

cc @candonov

**Comment by candonov** [comment]
We have built sufficient parity. Closing this and will track the rest in separate issues.
